from __future__ import annotations

from typing import List

from .factors import (
    MeanReversion,
    Momentum,
    Volatility,
    DollarVolume,
    Size,
    EarningsYield,
    Profitability,
    DividendYield,
    Beta,
    DownsideBeta,
    AnalystRevision,
    EarningsSurprise,
    Turnover,
    DownsideVol,
    High52wProximity,
    AmihudIlliquidity,
    AmihudIlliquidityLog,
    BookToPrice,
    ReturnOnAssets,
    Leverage,
    SalesGrowth,
    AssetGrowth,
    ResidualVol,
    IdiosyncraticVolatility,
    ResidualMomentum,
    EfficiencyRatio,
    GrossProfitability,
    SalesGrowthAcceleration,
    NetBuybackYield,
    CashflowYield,
    FreeCashflowYield,
    Accruals,
    RDIntensity,
    NetIssuance,
    ReturnSkewness,
    ReturnKurtosis,
    DividendGrowth,
)


def get_default_factors() -> List:
    """
    Central place to declare the default factor set used by run_factors and demos.
    Modify or extend this list to add/remove factors without changing runner code.
    """
    return [
        Momentum(lookback_days=252, skip_days=21, name="momentum_12m"),
        ResidualMomentum(),
        Volatility(window=60, name="volatility_60d"),
        IdiosyncraticVolatility(window=60),
        DownsideVol(window=60),
        MeanReversion(lookback_days=5, name="mean_reversion_5d"),
        High52wProximity(),
        DollarVolume(window=20, name="dollar_volume_20d"),
        AmihudIlliquidity(window=20),
        AmihudIlliquidityLog(window=20),
        EfficiencyRatio(window=252),
        ResidualVol(window=252),
        Size(),
        EarningsYield(),
        Profitability(),
        DividendYield(),
        Beta(window=252),
        DownsideBeta(window=252),
        CashflowYield(),
        FreeCashflowYield(),
        GrossProfitability(),
        Accruals(),
        RDIntensity(),
        NetIssuance(),
        NetBuybackYield(),
        ReturnSkewness(),
        ReturnKurtosis(),
        DividendGrowth(),
        BookToPrice(),
        ReturnOnAssets(),
        Leverage(),
        SalesGrowth(),
        SalesGrowthAcceleration(),
        AssetGrowth(),
        AnalystRevision(),
        EarningsSurprise(),
        Turnover(),
    ]
